### ISSUE TITLE
FIX randomly miss super-tabs on load

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#116]

**Comment by vdias38** [comment]
See https://github.com/ionic-team/ionic/issues/12592

**Comment by danconte72** [comment]
- migrate parsers from eua to europe account;

**Comment by danconte72** [comment]
Testing, when the headers are not showed, the swipe movements works.

**Comment by danconte72** [comment]
I've tested with ion-tabs:
- the error it not happens;
- to keep visual I recommend use mode="wp";
- [example](https://github.com/ionic-team/ionic/blob/fa554eba41c346e140d741ee340828595ed17c80/demos/src/tabs/pages/page-one/page-one.html#L11) ;
- use tabsPlacement="top";

**Comment by danconte72** [comment]
I've updated super-tabs to 4.3.0 and the behavior persists

**Comment by danconte72** [comment]
We can use icons in order to avoid translation

**Comment by danconte72** [comment]
two alternative scenarios
- move to ion-tabs:
  - translation ok;
  - swipe nok;
- stay on super-tabs: (please [test](https://github.com/meumobi/ion-employee/tree/fix/missing-tabs) 
  - translation nok:
    - we can use icons;
    - [or] temporarily use only on pt-br (until find out a better solution);
  - swipe ok;

**Comment by danconte72** [comment]
- temporarily we will use only on pt-br (until find out a better solution) keeping swipe tabs

**Comment by vdias38** [comment]
Should find a solution because we'll use it for foreign languages

**Comment by danconte72** [comment]
should test if error keep happening, if true, test  adding space workaround

**Comment by danconte72** [comment]
I've translate the tabs title and the error not happened.

Tests:
1. clear site data, remove www, run ionic serve
2. login with user with pt language
tabs showed and translated
3. update user language to en
tabs showed and translated
3. logout
4. login with user with en language
tabs showed and translated
5. logout
6. clear site data, remove www, run ionic serve
7.  login with user with en language
tabs showed and translated

I've removed my user from db 
1. login with new user without language preference
tabs showed and translated pt, default preferredLanguage = 'pt';
I've set on db an invalid lang 'es'
2. tabs showed and translated en (default language)

I've commented default language https://github.com/meumobi/ion-employee/blob/d3f10a309af26983c21a742dd6bd3bf1483181fe/src/app/app.component.ts#L82
And re-tested
1. clear site data, remove www, run ionic serve
2. login with user with pt language
tabs showed and translated
3. update user language to en
tabs showed and translated

**Comment by vdias38** [comment]
bug re-appears on latest release

**Comment by danconte72** [comment]
## how to reproduce 
- In order to force a delay on translations load I've upload translations copies to s3;
- To test just update the following line
https://github.com/meumobi/infomobi/blob/5719bb25edb82065216ccd03fe25602ca94def43/src/app/app.module.ts#L40 
from `./assets/i18n/ ` to `https://s3-sa-east-1.amazonaws.com/infomobi/i18n/`
- In the first load, tabs header aren't loaded 
![image](https://user-images.githubusercontent.com/32454870/55571994-0ac5b100-56dd-11e9-9346-e30043374023.png)
- if click home on side menu, tabs are showed 
![image](https://user-images.githubusercontent.com/32454870/55572047-2630bc00-56dd-11e9-93df-5fb952b323ad.png)

**Comment by danconte72** [comment]
## why it happens
- This happens because if all tabs have empty titles, headers are not rendered;
- Sometimes translations take a long time to be loaded, resulting a empty title before tabs render;

## how to fix
- to make assure that is at least a valid title
on 'home.html' add a space into title after translate

FROM
```html
    <super-tab [root]="live" title="{{'HOME.LIVE' | translate}}"></super-tab>
```
TO
```html
    <super-tab [root]="live" title="{{'HOME.LIVE' | translate}} "></super-tab>
```
