### ISSUE TITLE
settings link duplicated on sidemenu

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#312]
### Expected behaviour
Tell us what should happen

### Actual behaviour
![infomobi__improve_employee_experience_and_ion-employee_ _-bash_ _100x42](https://user-images.githubusercontent.com/9011612/53423995-3ff22b80-39da-11e9-98ed-0819b8cc08e3.png)

### Steps to reproduce
Only occurs if profile.role=admin
1. login
2. logout
3. login, open sidemenu

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
isAdmin pipe is called once for each login

**Comment by danconte72** [comment]
I've remove the appIsAdmin directive and the error not happened 

If I add appIsAdmin directive in another elements. It will duplicate
![image](https://user-images.githubusercontent.com/32454870/54030074-38c0df80-4189-11e9-9d3a-3b2199ca80b4.png)

If I perform a logout/login more times, it will render a new element for each time 
![image](https://user-images.githubusercontent.com/32454870/54030249-b97fdb80-4189-11e9-9810-36fb9ac307ae.png)


But it not happens if I reload the page. When I reload the element is rendered once.

**Comment by danconte72** [comment]
I've add a log for ever time an element is rendered on directive, and it increments every login, the number of calls to directive is the same, but it renders bases on a observable

**Comment by danconte72** [comment]
If I edit my data after save it will duplicate the elements

**Comment by danconte72** [comment]
https://stackoverflow.com/questions/41826478/do-i-have-to-unsubscribe-from-completed-observable 

If an observable is completed, all subscribers unsubscribe automatically.
The directives listen to userProfileService.getUserProfileObserver()
If on logout we complete this observable all subscriptions for it will be unsubscribed.

We can to this because getUserProfileObserver returns a BehaviorSubject asObservable;

We must to call userProfileService.[finish, complete, logout] and in this function perform a current$.complete()

I've tested and it worked, is less code than set a var do keep the subscription and track the correct event to unsubscribe this subscription

**Comment by danconte72** [comment]
On logout event we can call userProfileService.[finish, complete, logout]

**Comment by vdias38** [comment]
My suggestion:
`authService.signOut` call `userProfileService.complete()`

and remove all unsubscription of userProfile Observer

**Comment by vdias38** [comment]
Better... call `userProfile.signOut()` on `app.component` as you suggested.
`authService`  is only responsible for meumobi authentication, should not handle user profile (firebase)

**Comment by danconte72** [comment]
Ideally we must to reset the service or at least the behavior subject on login event

- restart [service](https://stackoverflow.com/questions/44383581/how-i-can-reload-restart-service-in-angular);
- restart behavior  `this.current$ = new BehaviorSubject<UserProfile>(new UserProfile()); `

**Comment by vdias38** [comment]
The issue occurs because userProfile remains not null when signOut. Then if re-signIn the directive create a new element.
Therefore `app.component` should "signOut userProfile" (set null), that should clear element, AND pause to listen userProfile stream

**Comment by vdias38** [comment]
We should follow example of [`ngIf` directive](https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_if.ts), and `// clear previous view if any` before `viewContainer.createEmbeddedView`

**Comment by danconte72** [comment]
test following ngIf directive example
