### ISSUE TITLE
Add the Ladda loading indicator on all Submit buttons

### ISSUE THREAD

**Issue by elbidone** [meumobi/infomobi#61]
See an example of implementation
http://www.sitepoint.com/taking-angular-mobile-ui-cross-platform-apps/

**Comment by vanlopes** [comment]
created branch ```infobox_ladda``` first commit is febf2ed6dd77af864bdb799d7c0d351a5c036ad1

Created js and directives for the component

**Comment by vanlopes** [comment]
Testing https://github.com/remotty/angular-ladda, it seems like a wrapper from the component.

**Comment by vanlopes** [comment]
Testing the http://www.sitepoint.com/taking-angular-mobile-ui-cross-platform-apps/ solution gives me an error: 

```TypeError: undefined is not a function
    at createSpinner (app.min.js:33875)
    at Object.instance.start (app.min.js:33556)
    at Object.fn (app.min.js:37996)
```
Right inside ladda.js file.

**Comment by elbidone** [comment]
it seems strange, because this project is popular. Are you sure you've added the module correctly ? You should achieve it through bower and add it correctly on gulp to merge js? gulp of infobox doesn't merge css, only less

**Comment by t4deu** [comment]
Hello guys,
The error related was because the libs has been included in the wrong order.

The spin.min.js must be included before the ladda.js

**Comment by elbidone** [comment]
check the vButton angular directive
http://codepen.io/LukaszWatroba/pen/YPNvpX

**Comment by elbidone** [comment]
ladda have more contributors than v-button and more activity. 
Added on Account/changePassword
Missing on Poll/vote and Contact/mail

**Comment by elbidone** [comment]
Done on Contact/mail

**Comment by elbidone** [comment]
Done on Poll/vote
Done modal/ChangePassword

**Comment by danconte72** [comment]
PWA:
- How to track PWA and offline events on [GA](https://medium.com/dev-channel/tracking-pwa-events-with-google-analytics-3b50030d8922):
  - There is a offline module on GA: (depreciated)
    - Its save 24 hours requests;
  - To catch GA requests when a user is offline, you must to use a service worker to intercept them;
- [Workbox](https://developers.google.com/web/tools/workbox/):
  - Google JavaScript Libraries for adding offline support to web apps;
  - [Codelab](https://codelabs.developers.google.com/codelabs/workbox-lab/#0) Build a PWA using Workbox;
  - Ionic with [Workbox](https://golb.hplar.ch/2017/11/Ionic-with-Workbox-Service-Worker.html);
- Workbox Google Analytics: ([latest](https://developers.google.com/web/tools/workbox/modules/workbox-google-analytics))

**Comment by vdias38** [comment]
# Using Ionic/Cordova app sources as PWA: Adding Google Analytics
There are two ways to add Google Analytics on Ionic dual App/PWA:
- raw Analytics
- [google-analytics-plugin](https://github.com/danwilson/google-analytics-plugin)

> I use raw Google Analytics, for each page I override onViewEnter() method and send a pageview message to GA with custom URL.

Source: [Adding Google Analytics to a PWA](https://forum.ionicframework.com/t/adding-google-analytics-to-a-pwa-ionic-3/93574/5)

> Many links on Ionic forum led to the implementation of GA through Cordova plugin
It actually works in the `platforms/browser/www/` directory after building with :
`ionic cordova build browser --prod`

Source: [Google Analytics implementation on PWA site](https://forum.ionicframework.com/t/google-analytics-implementation-on-pwa-site/99325/3)

The `google-analytics-plugin` is well documented and its integration is pretty straight forward, it's why I highly recommend it if you target only Apps. Considering PWA performance, the use of cordova plugin and consequently the build of cordva browser platform significantly increase the size of build. It's why below I develop the integration of raw Google Analytics, attending any build App (iOS, Android) and PWA.

# Setup raw Google Analytics
Sources:
- [Using Google Analytics in an Ionic app without a plugin](https://www.27partners.com/2016/07/using-google-analytics-in-an-ionic-app-without-a-plugin/)
- [How to use Google Analytics with Phonegap without a plugin?](https://stackoverflow.com/a/42216498/4982169)
## File URL support
The problem turned out to be that GA was checking to see whether the current browser protocol was `http://` or `https://` so it could match it. In an Ionic app the protocol is actually `file://` so this needed to be circumvented. ​

## Disables cookies
Android 5.0+ doesn’t support third party cookies by default, so you should use localStorage for persisting the clientId.

# Track View

# Track Event
